version: "3"

services:
  pg-database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .env